"""Add resources table

Revision ID: 14bb851be813
Revises: bacf55c005d2
Create Date: 2024-10-17 19:44:27.608396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bb851be813'
down_revision: Union[str, None] = 'bacf55c005d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_user_id_fkey', 'resource', type_='foreignkey')
    op.create_foreign_key(None, 'resource', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resource', 'upload_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.create_foreign_key('resource_user_id_fkey', 'resource', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
