"""Add user role for user_workspace table

Revision ID: bacf55c005d2
Revises: 
Create Date: 2024-09-29 15:03:15.416738

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy import MetaData

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacf55c005d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('user_work_space', sa.Column('role', sa.Enum('owner', 'admin', 'viewer', name='role'), nullable=False, server_default='owner'))
#     # ### end Alembic commands ###

def upgrade():
    # Define the ENUM type
    role_enum = ENUM('owner', 'admin', 'viewer', name='role', create_type=True, metadata=MetaData())
    
    # Create ENUM in the database
    role_enum.create(op.get_bind(), checkfirst=True)
    
    # Add the column with the ENUM type
    op.add_column('user_work_space', sa.Column('role', role_enum, nullable=False, server_default='owner'))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_work_space', 'role')
    # ### end Alembic commands ###
